# Generated by Django 4.2.30 on 2026-04-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("lecturer", models.CharField(max_length=100)),
                ("credits", models.PositiveIntegerField(default=10)),
                ("weekday", models.CharField(max_length=20)),
                ("start_time", models.CharField(max_length=20)),
                ("end_time", models.CharField(max_length=20)),
                ("classroom", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="enrolled_courses",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="core.course"
            ),
        ),
    ]
