# Generated by Django 4.2.30 on 2026-04-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_student_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="course",
            new_name="major",
        ),
    ]
